apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  labels:
    app: main-app
spec:
  selector:
    matchLabels:
      app: main-app
  replicas: 1
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - name: main-app
        image: namuk2004/main_app
        env:
        - name: movie-informer-ip
          value: new-movie-svc
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: main-app-svc
spec:
  sessionAffinity: ClientIP
  selector:
    app: main-app
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: NodePort
